Cruz_Saco/Models/Historial.cs
using DocumentFormat.OpenXml.Drawing.Charts;
using System;

namespace Cruz_Saco.Models
{
    public class Historial
    {
        public int Nro_Cuota { get; set; }
        public string Mes { get; set; }
        public DateTime Fecha_Vencimiento { get; set; }
        public string Fecha_Pago { get; set; }
        public string Hora_Pago { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
    }
}

Cruz_Saco/Controllers/ConsultaPagosClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using Cruz_Saco.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System;

namespace Cruz_Saco.Controllers
{
    public class ConsultaPagosClienteController : Controller
    {
        private readonly IConfiguration _config;

        public ConsultaPagosClienteController(IConfiguration config)
        {
            _config = config;
        }
        public IActionResult PagoCliente()
        {
            string _connectionString = _config.GetConnectionString("cn");

            int XUsuario = int.Parse(HttpContext.Session.GetString("Usuario").ToString());

            int codigo_apode = 0;

            using (var connection = new SqlConnection(_connectionString))
            {
                connection.Open();

                var command = new SqlCommand("sp_obtener_codigo_apoderado", connection);
                command.CommandType = CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@xUsuario", XUsuario);

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        codigo_apode = Convert.ToInt32(reader.GetValue(0));
                    }
                }


                // Obtener la lista de pagos del apoderado 
                var pagos = new List<PagosClienteClass>();

                using (var connection2 = new SqlConnection(_connectionString))
                {
                    connection2.Open();

                    var command2 = new SqlCommand("sp_VerPagosPagados", connection);
                    command2.CommandType = CommandType.StoredProcedure;
                    command2.Parameters.AddWithValue("@apoderado", codigo_apode);

                    using (var reader2 = command2.ExecuteReader())
                    {
                        while (reader2.Read())
                        {
                            var pago = new PagosClienteClass();

                            pago.Apoderado = reader2.GetString(0);
                            pago.Parentesco = reader2.GetString(1);
                            pago.Estudiante = reader2.GetString(2);
                            pago.Concepto = reader2.GetString(3);
                            pago.FechaPago = reader2.GetString(4);
                            pago.HoraPago = reader2.GetString(5);
                            pago.Monto = reader2.GetDecimal(6);
                            pago.Descuento = reader2.GetDecimal(7);
                            pago.AjusteManual = reader2.GetString(8);

                            pagos.Add(pago);
                        }
                    }
                }

                return View(pagos);
            }

        }

        public IActionResult Historial()
        {
            string _connectionString = _config.GetConnectionString("cn");
            int XUsuario = int.Parse(HttpContext.Session.GetString("Usuario").ToString());
            int codigo_apode = 0;

            using (var connection = new SqlConnection(_connectionString))
            {
                connection.Open();

                var command = new SqlCommand("sp_obtener_codigo_apoderado_estudiante", connection);
                command.CommandType = CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@xUsuario", XUsuario);

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        codigo_apode = Convert.ToInt32(reader.GetValue(0));
                    }
                }

                var historial = new List<Historial>();
                using (var connection2 = new SqlConnection(_connectionString))
                {
                    connection2.Open();

                    var command2 = new SqlCommand("sp_VerPagosPendientes", connection2);
                    command2.CommandType = CommandType.StoredProcedure;
                    command2.Parameters.AddWithValue("@anio", 2023);
                    command2.Parameters.AddWithValue("@estudiante", codigo_apode);
                    

                    using (var reader2 = command2.ExecuteReader())
                    {
                        while (reader2.Read())
                        {
                            var historial1 = new Historial();

                            historial1.Nro_Cuota = Convert.ToInt32(reader2.GetValue(0));
                            historial1.Mes = reader2.GetString(1);
                            historial1.Fecha_Vencimiento = reader2.GetDateTime(2);
                            historial1.Fecha_Pago = reader2.GetString(3);
                            historial1.Hora_Pago = reader2.GetString(4);
                            historial1.Monto = reader2.GetDecimal(5);
                            historial1.Estado = reader2.GetString(6);

                            historial.Add(historial1);
                        }
                    }
                }
                return View(historial);
            } 
        }

        public IActionResult HistorialAdmin(int estudiante)
        {
            string _connectionString = _config.GetConnectionString("cn");

            // Obtener la lista de apoderados
            List<Apoderado> apoderados = new List<Apoderado>();
            string query = "select\r\nca.codigo,\r\nconcat(ca.apellido_paterno,' ',ca.apellido_materno,', ',ca.nombre) as nombre\r\nfrom Cliente_Apoderado ca";

            using (SqlConnection cn = new SqlConnection(_connectionString))
            {
                cn.Open();
                SqlCommand cmd = new SqlCommand(query, cn);

                using (SqlDataReader read = cmd.ExecuteReader())
                {
                    while (read.Read())
                    {
                        apoderados.Add(new Apoderado { Código = read.GetInt32(0), Nombre = read.GetString(1) });
                    }
                }
            }

            // Agregar la lista de apoderados al ViewBag para enviarla a la vista
            ViewBag.Apoderados = new SelectList(apoderados, "Código", "Nombre");

            // Obtener la lista de pagos del apoderado seleccionado
            var historial = new List<Historial>();
            using (var connection = new SqlConnection(_connectionString))
            {
                connection.Open();

                var command = new SqlCommand("sp_VerPagosPendientes", connection);
                command.CommandType = CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@anio", 2023);
                command.Parameters.AddWithValue("@estudiante", estudiante);

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var pago = new Historial();

                        pago.Nro_Cuota = Convert.ToInt32(reader.GetValue(0));
                        pago.Mes = reader.GetString(1);
                        pago.Fecha_Vencimiento = reader.GetDateTime(2);
                        pago.Fecha_Pago = reader.GetString(3);
                        pago.Hora_Pago = reader.GetString(4);
                        pago.Monto = reader.GetDecimal(5);
                        pago.Estado = reader.GetString(6);

                        historial.Add(pago);
                    }
                }
            }

            return View(historial);
        }

    }
}

Cruz_Saco/Views/ConsultaPagosCliente/Historial.cshtml
@model IEnumerable<Cruz_Saco.Models.Historial>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Historial</title>
    <script type="text/javascript">

    $(function () 
    {        
        $.ajax({
            type: "POST",
            url: '@Url.Action("ListarMenu","Home")',
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
            
                // variable que acumulará la construccion del menu dinamico
                var html = '';

                // variable que me ayuda a controlar la iteracion, si es un cambio de padre/opcion principal
                var Cod_Padre = -1;

                data.forEach(function (item) 
                {
                    //debugger;
                    // Es un registro de tipo padre?
                    if (item.cod_Padre == 0)
                    {
                        if (Cod_Padre != -1)
                        {
                            html = html + '</div>' +
                                '</li>';
                        }

                        Cod_Padre = item.cod_Padre

                        html = html + '<li class="nav-item dropdown">' +
                            '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' +
                            item.nombre +
                            '</a>' +
                            '<div class="dropdown-menu" aria-labelledby="navbarDropdown">';
                    }
                    else
                    {
                        html = html + '<a class="dropdown-item" href="' + item.ruta + '">' + item.nombre + '</a>';
                    }
                });

                // Completo el cierre de etiquetas div y li de la ultima iteracion
                html = html + '</div>' +
                                '</li>';

                // Agrego estaticamente la opcion de cerrar sesion
                html = html + '<li class="nav-item">' +
                    '<a class="nav-link text-dark" href="/Seguridad/Index">Cerrar Sesión</a>' +
                    '</li>';

                // Inserto la variable html dentro del elemento ul
                $("#ulOpciones").append(html);

            },
            error: function () {
                alert("Error while inserting data");
            }
        });
    });

</script>
</head>
<body>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nro_Cuota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_Vencimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_Pago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora_Pago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nro_Cuota)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Vencimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Pago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora_Pago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            
        </tr>
}
    </tbody>
</table>
</body>
</html>

Cruz_Saco/Views/ConsultaPagosCliente/HistorialAdmin.cshtml
@model IEnumerable<Cruz_Saco.Models.Historial>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HistorialAdmin</title>
    <style>
        spam, input {
            margin: 10px
        }
    </style>
</head>
<body>
    <h2>Informe de Pagos</h2>
    @using (Html.BeginForm("HistorialAdmin", "ConsultaPagosCliente", FormMethod.Get))
    {
        <div>
            <label>Apoderado:</label>
            @Html.DropDownList("estudiante", ViewBag.Apoderados as SelectList,"Seleccione un cliente", new { @class = "form-control" })

            <input type="submit" value="Buscar" class="btn btn-primary" />
        </div>
    }

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nro_Cuota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_Vencimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_Pago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora_Pago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nro_Cuota)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Vencimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Pago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora_Pago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
<script type="text/javascript">

    $(function () 
    {        
        $.ajax({
            type: "POST",
            url: '@Url.Action("ListarMenu","Home")',
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
            
                // variable que acumulará la construccion del menu dinamico
                var html = '';

                // variable que me ayuda a controlar la iteracion, si es un cambio de padre/opcion principal
                var Cod_Padre = -1;

                data.forEach(function (item) 
                {
                    //debugger;
                    // Es un registro de tipo padre?
                    if (item.cod_Padre == 0)
                    {
                        if (Cod_Padre != -1)
                        {
                            html = html + '</div>' +
                                '</li>';
                        }

                        Cod_Padre = item.cod_Padre

                        html = html + '<li class="nav-item dropdown">' +
                            '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' +
                            item.nombre +
                            '</a>' +
                            '<div class="dropdown-menu" aria-labelledby="navbarDropdown">';
                    }
                    else
                    {
                        html = html + '<a class="dropdown-item" href="' + item.ruta + '">' + item.nombre + '</a>';
                    }
                });

                // Completo el cierre de etiquetas div y li de la ultima iteracion
                html = html + '</div>' +
                                '</li>';

                // Agrego estaticamente la opcion de cerrar sesion
                html = html + '<li class="nav-item">' +
                    '<a class="nav-link text-dark" href="/Seguridad/Index">Cerrar Sesión</a>' +
                    '</li>';

                // Inserto la variable html dentro del elemento ul
                $("#ulOpciones").append(html);

            },
            error: function () {
                alert("Error while inserting data");
            }
        });
    });

</script>

</body>
</html>

Cruz_Saco/Views/ConsultaPagosCliente/PagoCliente.cshtml
@model IEnumerable<Cruz_Saco.Models.PagosClienteClass>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PagoCliente</title>
    <script type="text/javascript">

    $(function () 
    {        
        $.ajax({
            type: "POST",
            url: '@Url.Action("ListarMenu","Home")',
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (data) {
            
                // variable que acumulará la construccion del menu dinamico
                var html = '';

                // variable que me ayuda a controlar la iteracion, si es un cambio de padre/opcion principal
                var Cod_Padre = -1;

                data.forEach(function (item) 
                {
                    //debugger;
                    // Es un registro de tipo padre?
                    if (item.cod_Padre == 0)
                    {
                        if (Cod_Padre != -1)
                        {
                            html = html + '</div>' +
                                '</li>';
                        }

                        Cod_Padre = item.cod_Padre

                        html = html + '<li class="nav-item dropdown">' +
                            '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' +
                            item.nombre +
                            '</a>' +
                            '<div class="dropdown-menu" aria-labelledby="navbarDropdown">';
                    }
                    else
                    {
                        html = html + '<a class="dropdown-item" href="' + item.ruta + '">' + item.nombre + '</a>';
                    }
                });

                // Completo el cierre de etiquetas div y li de la ultima iteracion
                html = html + '</div>' +
                                '</li>';

                // Agrego estaticamente la opcion de cerrar sesion
                html = html + '<li class="nav-item">' +
                    '<a class="nav-link text-dark" href="/Seguridad/Index">Cerrar Sesión</a>' +
                    '</li>';

                // Inserto la variable html dentro del elemento ul
                $("#ulOpciones").append(html);

            },
            error: function () {
                alert("Error while inserting data");
            }
        });
    });

</script>
</head>
<body>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Apoderado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parentesco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estudiante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Concepto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraPago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descuento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AjusteManual)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Apoderado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parentesco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estudiante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Concepto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraPago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descuento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AjusteManual)
            </td>
            
        </tr>
}
    </tbody>
</table>

</body>
</html>